import Colors from "@/constants/Colors";
import { FontAwesome6 } from "@expo/vector-icons";
import { useFocusEffect } from "@react-navigation/native";
import { Stack, useLocalSearchParams, useRouter } from "expo-router";
import React, { useCallback, useEffect, useState } from "react";
import {
    ActivityIndicator,
    Alert,
    FlatList,
    Image,
    Modal,
    Pressable,
    StyleSheet,
    Switch,
    Text,
    TouchableOpacity,
    View,
} from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { supabase } from "../../supabaseClient";
import { getCommunityById, getCommunityName } from "../../utils/communities";
import { useAuth } from "../../contexts/AuthContext";
import { useAppTheme } from "../../contexts/ThemeContext";
import { loginRoute, withSearchParams } from "../../utils/authRedirect";
import PhotoCarousel from "../../components/PhotoCarousel";

const getInitials = (name: string) => {
  const parts = (name || "").trim().split(/\s+/).filter(Boolean);
  const first = parts[0]?.replace(/[^A-Za-zÇĞİÖŞÜçğıöşü]/g, "").charAt(0) || "U";
  const last =
    parts.length > 1
      ? parts[parts.length - 1]?.replace(/[^A-Za-zÇĞİÖŞÜçğıöşü]/g, "").charAt(0)
      : "";
  return `${first}${last}`.toLocaleUpperCase("tr-TR");
};

const isGeneratedAvatar = (avatar?: string | null) => {
  if (!avatar) return true;
  const normalized = avatar.toLocaleLowerCase("tr-TR");
  return (
    normalized.includes("ui-avatars.com") ||
    normalized.includes("pravatar") ||
    normalized.includes("placeholder")
  );
};

const shouldShowPost = (item: any) => {
  const combined = [
    item.user,
    item.avatar,
    item.car,
    item.title,
    item.content,
  ]
    .filter(Boolean)
    .join(" ")
    .toLowerCase();

  return (
    !combined.includes("test kullanıcısı") &&
    !combined.includes("pravatar") &&
    !combined.includes("placeholder") &&
    !combined.includes("mock")
  );
};

const hasAutoGeneratedTitle = (item: any) =>
  Boolean(
    item.community_id &&
      item.content &&
      item.title === item.content.trim().replace(/\s+/g, " ").slice(0, 80),
  );

export default function CommunityFeedScreen() {
  const { id } = useLocalSearchParams<{ id: string }>();
  const router = useRouter();
  const { user, isLoggedIn } = useAuth();
  const { palette } = useAppTheme();

  // Expo Router'da parametreler ilk renderda undefined veya dizi gelebilir.
  const rawCommunityId = Array.isArray(id) ? id[0] : id;
  const communityId =
    typeof rawCommunityId === "string" &&
    rawCommunityId.trim() &&
    rawCommunityId !== "[id]"
      ? rawCommunityId.trim()
      : "";

  const [posts, setPosts] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const [settingsVisible, setSettingsVisible] = useState(false);
  const [isMember, setIsMember] = useState(false);
  const [showProfile, setShowProfile] = useState(true);
  const [useBadge, setUseBadge] = useState(true);
  const [notify, setNotify] = useState(true);
  const [memberCount, setMemberCount] = useState(0);

  const community = getCommunityById(communityId);
  const communityName = community?.name || getCommunityName(communityId);
  const createPostReturnTo = withSearchParams("/post/create", { communityId });

  const goToCreatePost = () => {
    if (!isLoggedIn) {
      router.push(loginRoute(createPostReturnTo) as any);
      return;
    }

    router.push({
      pathname: "/post/create",
      params: { communityId },
    } as any);
  };

  const fetchPosts = useCallback(
    async (showLoader = true) => {
      if (!communityId || !getCommunityById(communityId)) {
        setPosts([]);
        if (showLoader) setLoading(false);
        return;
      }

      try {
        if (showLoader) setLoading(true);
        const { data, error } = await supabase
          .from("posts")
          .select("*")
          .eq("community_id", communityId)
          .not("user_id", "is", null)
          .order("created_at", { ascending: false })
          .limit(20);

        if (error) {
          console.error(
            "Supabase'den postlar çekilirken hata oluştu:",
            error.message,
          );
          return;
        }

        if (data) {
          const visiblePosts = data.filter(shouldShowPost);
          const postIds = visiblePosts.map((post: any) => post.id).filter(Boolean);

          if (postIds.length > 0) {
            const { data: commentRows, error: commentsError } = await supabase
              .from("comments")
              .select("post_id")
              .in("post_id", postIds);

            if (commentsError) {
              console.error(
                "Topluluk yorum sayıları alınamadı:",
                commentsError.message,
              );
              setPosts(visiblePosts);
              return;
            }

            const countsByPostId = (commentRows || []).reduce(
              (acc: Record<string, number>, row: any) => {
                if (!row.post_id) return acc;
                acc[row.post_id] = (acc[row.post_id] || 0) + 1;
                return acc;
              },
              {},
            );

            setPosts(
              visiblePosts.map((post: any) => ({
                ...post,
                comments: countsByPostId[post.id] || 0,
              })),
            );
          } else {
            setPosts(visiblePosts);
          }
        }
      } catch (err) {
        console.error("Beklenmeyen hata:", err);
      } finally {
        if (showLoader) setLoading(false);
      }
    },
    [communityId],
  );

  useEffect(() => {
    fetchPosts();
  }, [fetchPosts]);

  useFocusEffect(
    useCallback(() => {
      fetchPosts(false);
      const timer = setTimeout(() => {
        fetchPosts(false);
      }, 800);

      return () => clearTimeout(timer);
    }, [fetchPosts]),
  );

  useEffect(() => {
    if (!communityId || !community) return;

    const channelSuffix = [
      user?.id || "guest",
      Date.now(),
      Math.random().toString(36).slice(2),
    ].join(":");

    const postsChannel = supabase
      .channel(`community-detail:posts:${communityId}:${channelSuffix}`)
      .on(
        "postgres_changes",
        {
          event: "*",
          schema: "public",
          table: "posts",
          filter: `community_id=eq.${communityId}`,
        },
        (payload) => {
          if (payload.eventType === "INSERT") {
            const nextPost = payload.new;
            if (!shouldShowPost(nextPost)) return;

            setPosts((prev) => {
              if (prev.some((post) => post.id === nextPost.id)) return prev;
              return [nextPost, ...prev].slice(0, 20);
            });
          } else if (payload.eventType === "UPDATE") {
            const nextPost = payload.new;
            setPosts((prev) => {
              if (!shouldShowPost(nextPost)) {
                return prev.filter((post) => post.id !== nextPost.id);
              }
              return prev.map((post) =>
                post.id === nextPost.id ? nextPost : post,
              );
            });
          } else if (payload.eventType === "DELETE") {
            setPosts((prev) =>
              prev.filter((post) => post.id !== payload.old.id),
            );
          }
        },
      )
      .subscribe();

    const commentsChannel = supabase
      .channel(`community-detail:comments:${communityId}:${channelSuffix}`)
      .on(
        "postgres_changes",
        {
          event: "*",
          schema: "public",
          table: "comments",
        },
        (payload) => {
          if (payload.eventType === "INSERT") {
            const postId = payload.new.post_id;
            if (!postId) return;

            setPosts((prev) =>
              prev.map((post) =>
                post.id === postId
                  ? { ...post, comments: Number(post.comments || 0) + 1 }
                  : post,
              ),
            );
          } else if (payload.eventType === "DELETE") {
            const postId = payload.old.post_id;
            if (!postId) return;

            setPosts((prev) =>
              prev.map((post) =>
                post.id === postId
                  ? {
                      ...post,
                      comments: Math.max(0, Number(post.comments || 0) - 1),
                    }
                  : post,
              ),
            );
          } else if (payload.eventType === "UPDATE") {
            fetchPosts(false);
          }
        },
      )
      .subscribe();

    return () => {
      supabase.removeChannel(postsChannel);
      supabase.removeChannel(commentsChannel);
    };
  }, [community, communityId, fetchPosts, user?.id]);

  useEffect(() => {
    const fetchMembership = async () => {
      if (!communityId || !community) {
        setIsMember(false);
        setMemberCount(0);
        return;
      }

      const { data: countData, error: countError } = await supabase.rpc(
        "get_community_member_count",
        { p_community_id: communityId },
      );

      if (countError) {
        console.error("Topluluk üye sayısı alınamadı:", countError.message);
        setMemberCount(0);
      } else {
        setMemberCount(Number(countData || 0));
      }

      if (!user?.id) {
        setIsMember(false);
        return;
      }

      const { data, error } = await supabase
        .from("community_memberships")
        .select(
          "show_on_profile, use_vehicle_badge, notifications_enabled",
        )
        .eq("user_id", user.id)
        .eq("community_id", communityId)
        .maybeSingle();

      if (error) {
        console.error("Topluluk üyeliği alınamadı:", error.message);
        setIsMember(false);
        return;
      }

      setIsMember(!!data);
      if (data) {
        setShowProfile(data.show_on_profile ?? true);
        setUseBadge(data.use_vehicle_badge ?? true);
        setNotify(data.notifications_enabled ?? true);
      }
    };

    fetchMembership();
  }, [community, communityId, user?.id]);

  if (!communityId || !community) {
    return (
      <SafeAreaView
        style={[styles.container, { backgroundColor: palette.background }]}
        edges={["top"]}
      >
        <Stack.Screen options={{ headerShown: false }} />
        <View style={styles.notFoundState}>
          <FontAwesome6 name="users-slash" size={28} color={Colors.orange} />
          <Text style={[styles.emptyTitle, { color: palette.text }]}>
            Topluluk bulunamadı
          </Text>
          <Text style={[styles.emptyText, { color: palette.muted }]}>
            Bu bağlantı geçersiz veya topluluk artık mevcut değil.
          </Text>
          <TouchableOpacity
            style={styles.emptyBtn}
            onPress={() => router.replace("/communities")}
          >
            <Text style={styles.emptyBtnText}>Topluluklara Dön</Text>
          </TouchableOpacity>
        </View>
      </SafeAreaView>
    );
  }

  const updateMembershipSetting = async (
    settings: Partial<{
      show_on_profile: boolean;
      use_vehicle_badge: boolean;
      notifications_enabled: boolean;
    }>,
  ) => {
    if (!isLoggedIn || !user?.id || !communityId) {
      router.push(loginRoute(`/community/${communityId}`) as any);
      return;
    }

    const { error } = await supabase.from("community_memberships").upsert(
      {
        user_id: user.id,
        community_id: communityId,
        show_on_profile: showProfile,
        use_vehicle_badge: useBadge,
        notifications_enabled: notify,
        ...settings,
      },
      { onConflict: "user_id,community_id" },
    );

    if (error) {
      Alert.alert("Hata", "Topluluk ayarı kaydedilemedi: " + error.message);
    }
  };

  const leaveCommunity = () => {
    if (!user?.id || !communityId) return;

    Alert.alert(
      "Topluluktan ayrıl",
      `${communityName} hızlı erişiminden ve üyeliklerinden kaldırılacak.`,
      [
        { text: "Vazgeç", style: "cancel" },
        {
          text: "Ayrıl",
          style: "destructive",
          onPress: async () => {
            const { error } = await supabase
              .from("community_memberships")
              .delete()
              .eq("user_id", user.id)
              .eq("community_id", communityId);

            if (error) {
              Alert.alert("Hata", "Topluluktan ayrılamadın: " + error.message);
              return;
            }

            setIsMember(false);
            setSettingsVisible(false);
            router.replace("/communities");
          },
        },
      ],
    );
  };

  return (
    <SafeAreaView
      style={[styles.container, { backgroundColor: palette.background }]}
      edges={["top"]}
    >
      <Stack.Screen options={{ headerShown: false }} />

      <View
        style={[
          styles.header,
          { backgroundColor: palette.background, borderBottomColor: palette.border },
        ]}
      >
        <TouchableOpacity
          onPress={() => router.back()}
          style={styles.headerBtn}
        >
          <FontAwesome6 name="arrow-left" size={18} color={palette.text} />
        </TouchableOpacity>
        <Text style={[styles.headerTitle, { color: palette.text }]}>
          c/{communityName}
        </Text>
        <TouchableOpacity
          style={styles.headerBtn}
          onPress={() => setSettingsVisible(true)}
        >
          <FontAwesome6 name="ellipsis-vertical" size={18} color={palette.text} />
        </TouchableOpacity>
      </View>

      {loading ? (
        <View
          style={{ flex: 1, justifyContent: "center", alignItems: "center" }}
        >
          <ActivityIndicator size="large" color={Colors.orange} />
        </View>
      ) : (
        <FlatList
          data={posts}
          keyExtractor={(item) => item.id.toString()}
          contentContainerStyle={styles.listContent}
          initialNumToRender={6}
          maxToRenderPerBatch={6}
          windowSize={5}
          removeClippedSubviews
          ListHeaderComponent={
            <View
              style={[
                styles.communityHero,
                { backgroundColor: palette.card, borderColor: palette.border },
              ]}
            >
              <View
                style={[
                  styles.communityIcon,
                  { backgroundColor: community?.iconBg || Colors.navyBorder },
                ]}
              >
                <FontAwesome6
                  name={(community?.icon as any) || "users"}
                  size={24}
                  color={community?.iconColor || Colors.orange}
                />
              </View>
              <View style={styles.communityHeroText}>
                <Text style={[styles.communityName, { color: palette.text }]}>
                  {communityName}
                </Text>
                <Text style={[styles.communityDesc, { color: palette.softText }]}>
                  {community?.description || "Topluluk akışı"}
                </Text>
                <Text style={[styles.communityStats, { color: palette.muted }]}>
                  {memberCount} üye {isMember ? "• Üyesin" : ""}
                </Text>
              </View>
            </View>
          }
          ListEmptyComponent={
            <View
              style={[
                styles.emptyCard,
                { backgroundColor: palette.card, borderColor: palette.border },
              ]}
            >
              <View style={styles.emptyIcon}>
                <FontAwesome6 name="comments" size={22} color={Colors.orange} />
              </View>
              <Text style={[styles.emptyTitle, { color: palette.text }]}>
                Henüz gönderi yok
              </Text>
              <Text style={[styles.emptyText, { color: palette.muted }]}>
                Bu kulübün ilk gerçek akışını sen başlatabilirsin.
              </Text>
              <TouchableOpacity
                style={styles.emptyBtn}
                onPress={goToCreatePost}
              >
                <Text style={styles.emptyBtnText}>İlk Gönderiyi Paylaş</Text>
              </TouchableOpacity>
            </View>
          }
          renderItem={({ item }) => {
            const isOwnPost = Boolean(user?.id && item.user_id === user.id);
            const authorName =
              isOwnPost && user?.name ? user.name : item.user || "Anonim";
            const authorAvatar =
              isOwnPost && user?.avatar ? user.avatar : item.avatar;
            const shouldShowAvatarImage = !isGeneratedAvatar(authorAvatar);

            return (
              <TouchableOpacity
                style={[
                  styles.postCard,
                  { backgroundColor: palette.card, borderColor: palette.border },
                ]}
                activeOpacity={0.8}
                onPress={() => router.push(`/post/${item.id}`)}
              >
                <TouchableOpacity
                  style={styles.postHeader}
                  activeOpacity={0.75}
                  onPress={() => {
                    if (item.user_id) router.push(`/user/${item.user_id}` as any);
                  }}
                >
                  {shouldShowAvatarImage ? (
                    <Image source={{ uri: authorAvatar }} style={styles.avatar} />
                  ) : (
                    <View
                      style={[
                        styles.avatarFallback,
                        { backgroundColor: palette.elevated },
                      ]}
                    >
                      <Text
                        style={[
                          styles.avatarFallbackText,
                          { color: palette.text },
                        ]}
                      >
                        {getInitials(authorName)}
                      </Text>
                    </View>
                  )}
                <View style={{ flex: 1 }}>
                  <View style={{ flexDirection: "row", alignItems: "center" }}>
                    <Text style={[styles.postAuthor, { color: palette.text }]}>
                      {authorName}
                    </Text>
                    {item.car ? (
                      <>
                        <Text style={[styles.postDot, { color: palette.muted }]}>
                          {" "}
                          •{" "}
                        </Text>
                        <Text style={styles.postCarBadge}>{item.car}</Text>
                      </>
                    ) : null}
                  </View>
                  <Text style={[styles.postTime, { color: palette.muted }]}>
                    {item.created_at
                      ? new Date(item.created_at).toLocaleDateString("tr-TR")
                      : "Yeni"}
                  </Text>
                </View>
              </TouchableOpacity>
              {!hasAutoGeneratedTitle(item) ? (
                <Text style={[styles.postTitle, { color: palette.text }]}>
                  {item.title}
                </Text>
              ) : null}
              {Array.isArray(item.topic_tags) && item.topic_tags.length > 0 ? (
                <View style={styles.topicTags}>
                  {item.topic_tags.map((tag: string) => (
                    <View
                      key={`${item.id}-${tag}`}
                      style={[
                        styles.topicTag,
                        { backgroundColor: palette.elevated, borderColor: palette.border },
                      ]}
                    >
                      <Text style={styles.topicTagText}>{tag}</Text>
                    </View>
                  ))}
                </View>
              ) : null}
              <Text
                style={[styles.postContent, { color: palette.softText }]}
                numberOfLines={3}
              >
                {item.content}
              </Text>
              {Array.isArray(item.images) && item.images.length > 0 ? (
                <PhotoCarousel
                  images={item.images}
                  height={220}
                  style={styles.postPhotoCarousel}
                />
              ) : null}
              <View
                style={[styles.interactionRow, { borderTopColor: palette.border }]}
              >
                <View style={styles.upvoteGroup}>
                  <FontAwesome6
                    name="arrow-up"
                    size={14}
                    color={palette.muted}
                  />
                  <Text style={[styles.upvoteCount, { color: palette.text }]}>
                    {item.upvotes || 0}
                  </Text>
                </View>
                <View style={styles.commentGroup}>
                  <FontAwesome6
                    name="message"
                    size={14}
                    color={palette.muted}
                  />
                  <Text style={[styles.commentCount, { color: palette.muted }]}>
                    {item.comments || 0} Yorum
                  </Text>
                </View>
                </View>
              </TouchableOpacity>
            );
          }}
        />
      )}

      <TouchableOpacity
        style={styles.fab}
        accessibilityRole="button"
        accessibilityLabel="Toplulukta yeni gönderi paylaş"
        activeOpacity={0.9}
        onPress={goToCreatePost}
      >
        <FontAwesome6 name="plus" size={20} color={Colors.white} />
      </TouchableOpacity>

      <Modal visible={settingsVisible} animationType="slide" transparent>
        <Pressable
          style={styles.modalOverlay}
          onPress={() => setSettingsVisible(false)}
        />
        <View
          style={[
            styles.modalSheet,
            { backgroundColor: palette.background, borderTopColor: palette.border },
          ]}
        >
          <View style={[styles.modalHandle, { backgroundColor: palette.border }]} />
          <Text style={[styles.modalTitle, { color: palette.text }]}>
            {communityName}
          </Text>
          <Text style={[styles.modalSubtitle, { color: palette.muted }]}>
            Topluluk ayarları
          </Text>

          {isMember ? (
            <>
              <View style={styles.modalRow}>
                <View style={styles.modalRowText}>
                  <Text style={[styles.modalRowTitle, { color: palette.text }]}>
                    Profilinde Göster
                  </Text>
                  <Text style={[styles.modalRowDesc, { color: palette.muted }]}>
                    Bu kulüp profilinde görünsün.
                  </Text>
                </View>
                <Switch
                  value={showProfile}
                  onValueChange={(value) => {
                    setShowProfile(value);
                    updateMembershipSetting({ show_on_profile: value });
                  }}
                  trackColor={{ false: palette.border, true: Colors.orange }}
                  thumbColor={Colors.white}
                />
              </View>
              <View style={[styles.modalDivider, { backgroundColor: palette.border }]} />
              <View style={styles.modalRow}>
                <View style={styles.modalRowText}>
                  <Text style={[styles.modalRowTitle, { color: palette.text }]}>
                    Araç Rozeti
                  </Text>
                  <Text style={[styles.modalRowDesc, { color: palette.muted }]}>
                    Gönderilerinde araç rozetini kullan.
                  </Text>
                </View>
                <Switch
                  value={useBadge}
                  onValueChange={(value) => {
                    setUseBadge(value);
                    updateMembershipSetting({ use_vehicle_badge: value });
                  }}
                  trackColor={{ false: palette.border, true: Colors.orange }}
                  thumbColor={Colors.white}
                />
              </View>
              <View style={[styles.modalDivider, { backgroundColor: palette.border }]} />
              <View style={styles.modalRow}>
                <View style={styles.modalRowText}>
                  <Text style={[styles.modalRowTitle, { color: palette.text }]}>
                    Bildirimler
                  </Text>
                  <Text style={[styles.modalRowDesc, { color: palette.muted }]}>
                    Bu kulüpteki hareketlerden haberdar ol.
                  </Text>
                </View>
                <Switch
                  value={notify}
                  onValueChange={(value) => {
                    setNotify(value);
                    updateMembershipSetting({ notifications_enabled: value });
                  }}
                  trackColor={{ false: palette.border, true: Colors.orange }}
                  thumbColor={Colors.white}
                />
              </View>
              <TouchableOpacity
                style={styles.leaveBtn}
                activeOpacity={0.85}
                onPress={leaveCommunity}
              >
                <FontAwesome6 name="right-from-bracket" size={14} color="#f87171" />
                <Text style={styles.leaveBtnText}>Topluluktan Ayrıl</Text>
              </TouchableOpacity>
            </>
          ) : (
            <View
              style={[
                styles.emptySettings,
                { backgroundColor: palette.card, borderColor: palette.border },
              ]}
            >
              <Text style={[styles.emptySettingsText, { color: palette.muted }]}>
                Bu topluluğun ayarlarını yönetmek için önce katılmalısın.
              </Text>
            </View>
          )}
        </View>
      </Modal>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: Colors.navyMain },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 10,
    paddingVertical: 12,
    backgroundColor: Colors.navyMain,
    borderBottomWidth: 1,
    borderBottomColor: Colors.navyBorder,
  },
  headerBtn: {
    width: 40,
    height: 40,
    justifyContent: "center",
    alignItems: "center",
  },
  headerTitle: { fontSize: 16, fontWeight: "700", color: Colors.white },
  listContent: { padding: 16, paddingBottom: 100 },
  communityHero: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: Colors.navyCard,
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: Colors.navyBorder,
    marginBottom: 16,
    gap: 12,
  },
  communityIcon: {
    width: 52,
    height: 52,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
  },
  communityHeroText: { flex: 1 },
  communityName: { color: Colors.white, fontSize: 18, fontWeight: "900" },
  communityDesc: {
    color: Colors.gray300,
    fontSize: 12,
    lineHeight: 17,
    marginTop: 3,
  },
  communityStats: {
    color: Colors.textMuted,
    fontSize: 11,
    fontWeight: "700",
    marginTop: 6,
  },
  emptyCard: {
    backgroundColor: Colors.navyCard,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: Colors.navyBorder,
    alignItems: "center",
    padding: 22,
    marginTop: 6,
  },
  emptyIcon: {
    width: 48,
    height: 48,
    borderRadius: 14,
    backgroundColor: "rgba(255,101,0,0.12)",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 12,
  },
  emptyTitle: { color: Colors.white, fontSize: 16, fontWeight: "800" },
  emptyText: {
    color: Colors.textMuted,
    fontSize: 13,
    textAlign: "center",
    lineHeight: 19,
    marginTop: 6,
    marginBottom: 14,
  },
  emptyBtn: {
    backgroundColor: Colors.orange,
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  emptyBtnText: { color: Colors.white, fontSize: 13, fontWeight: "800" },
  notFoundState: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 28,
    gap: 12,
  },
  postCard: {
    backgroundColor: Colors.navyCard,
    borderRadius: 16,
    padding: 16,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: Colors.navyBorder,
  },
  postHeader: { flexDirection: "row", alignItems: "center", marginBottom: 12 },
  avatar: {
    width: 36,
    height: 36,
    borderRadius: 18,
    marginRight: 10,
    backgroundColor: Colors.navyBorder,
  },
  avatarFallback: {
    width: 36,
    height: 36,
    borderRadius: 18,
    marginRight: 10,
    backgroundColor: Colors.navyBorder,
    alignItems: "center",
    justifyContent: "center",
  },
  avatarFallbackText: {
    color: Colors.white,
    fontSize: 13,
    fontWeight: "800",
  },
  postAuthor: { color: Colors.white, fontWeight: "700", fontSize: 14 },
  postDot: { color: Colors.textMuted, fontSize: 14 },
  postCarBadge: { color: Colors.orange, fontWeight: "700", fontSize: 13 },
  postTime: { color: Colors.textMuted, fontSize: 11, marginTop: 2 },
  postTitle: {
    color: Colors.white,
    fontSize: 16,
    fontWeight: "800",
    marginBottom: 8,
  },
  topicTags: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 6,
    marginBottom: 9,
  },
  topicTag: {
    borderRadius: 9,
    borderWidth: 1,
    paddingHorizontal: 9,
    paddingVertical: 5,
  },
  topicTagText: {
    color: Colors.orange,
    fontSize: 10,
    fontWeight: "700",
  },
  postContent: {
    color: Colors.gray300,
    fontSize: 13,
    lineHeight: 20,
    marginBottom: 16,
  },
  postPhotoCarousel: { marginBottom: 16 },
  interactionRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 16,
    borderTopWidth: 1,
    borderTopColor: Colors.navyBorder,
    paddingTop: 12,
  },
  upvoteGroup: { flexDirection: "row", alignItems: "center", gap: 6 },
  upvoteCount: { color: Colors.white, fontWeight: "700", fontSize: 13 },
  commentGroup: { flexDirection: "row", alignItems: "center", gap: 6 },
  commentCount: { color: Colors.textMuted, fontWeight: "700", fontSize: 13 },
  fab: {
    position: "absolute",
    bottom: 24,
    right: 20,
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: Colors.orange,
    justifyContent: "center",
    alignItems: "center",
    boxShadow: "0 4px 8px rgba(249, 115, 22, 0.4)",
    elevation: 5,
  },
  modalOverlay: { flex: 1, backgroundColor: "rgba(0,0,0,0.7)" },
  modalSheet: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: Colors.navyMain,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    padding: 22,
    paddingBottom: 34,
    borderTopWidth: 1,
    borderTopColor: Colors.navyBorder,
  },
  modalHandle: {
    width: 40,
    height: 4,
    borderRadius: 2,
    backgroundColor: Colors.navyBorder,
    alignSelf: "center",
    marginBottom: 18,
  },
  modalTitle: { color: Colors.white, fontSize: 20, fontWeight: "900" },
  modalSubtitle: { color: Colors.textMuted, fontSize: 13, marginTop: 4, marginBottom: 18 },
  modalRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 12,
  },
  modalRowText: { flex: 1, paddingRight: 12 },
  modalRowTitle: { color: Colors.white, fontSize: 14, fontWeight: "800" },
  modalRowDesc: { color: Colors.textMuted, fontSize: 12, lineHeight: 17, marginTop: 3 },
  modalDivider: { height: 1, backgroundColor: Colors.navyBorder },
  leaveBtn: {
    marginTop: 18,
    height: 48,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "rgba(248, 113, 113, 0.4)",
    backgroundColor: "rgba(248, 113, 113, 0.08)",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  leaveBtnText: { color: "#f87171", fontSize: 14, fontWeight: "800" },
  emptySettings: {
    borderWidth: 1,
    borderColor: Colors.navyBorder,
    backgroundColor: Colors.navyCard,
    borderRadius: 14,
    padding: 16,
  },
  emptySettingsText: { color: Colors.textMuted, fontSize: 13, lineHeight: 19 },
});
