import Colors from "@/constants/Colors";
import { FontAwesome6 } from "@expo/vector-icons";
import { Stack, useLocalSearchParams, useRouter } from "expo-router";
import React, { useEffect, useRef, useState } from "react";
import {
  ActivityIndicator,
  Alert,
  Image,
  KeyboardAvoidingView,
  Platform,
  Share,
  ScrollView,
  StyleSheet,
  Text,
  TextInput,
  TouchableOpacity,
  View,
} from "react-native";
import {
  SafeAreaView,
  useSafeAreaInsets,
} from "react-native-safe-area-context";
import { useAuth } from "../../contexts/AuthContext";
import { supabase } from "../../supabaseClient";
import { useAppTheme } from "../../contexts/ThemeContext";
import { validateCleanContent } from "../../utils/contentModeration";
import { reportContent } from "../../utils/moderation";
import { loginRoute } from "../../utils/authRedirect";
import PhotoCarousel from "../../components/PhotoCarousel";

const getInitials = (name: string) => {
  const parts = (name || "").trim().split(/\s+/).filter(Boolean);
  const first = parts[0]?.replace(/[^A-Za-zÇĞİÖŞÜçğıöşü]/g, "").charAt(0) || "U";
  const last =
    parts.length > 1
      ? parts[parts.length - 1]?.replace(/[^A-Za-zÇĞİÖŞÜçğıöşü]/g, "").charAt(0)
      : "";
  return `${first}${last}`.toLocaleUpperCase("tr-TR");
};

const isGeneratedAvatar = (avatar?: string | null) => {
  if (!avatar) return true;
  const normalized = avatar.toLocaleLowerCase("tr-TR");
  return (
    normalized.includes("ui-avatars.com") ||
    normalized.includes("pravatar") ||
    normalized.includes("placeholder")
  );
};

const hasAutoGeneratedTitle = (post: any) =>
  Boolean(
    post?.community_id &&
      post?.content &&
      post?.title === post.content.trim().replace(/\s+/g, " ").slice(0, 80),
  );

export default function PostDetailScreen() {
  const { id } = useLocalSearchParams<{ id: string }>();
  const router = useRouter();
  const [replyText, setReplyText] = useState("");
  const [replyingToComment, setReplyingToComment] = useState<any | null>(null);
  const inputRef = useRef<TextInput>(null);
  const scrollRef = useRef<ScrollView>(null);
  const { user } = useAuth();
  const { palette } = useAppTheme();
  const insets = useSafeAreaInsets();

  const scrollToComments = () => {
    setTimeout(() => scrollRef.current?.scrollToEnd({ animated: true }), 120);
  };

  const rawPostId = Array.isArray(id) ? id[0] : id;
  const postId =
    typeof rawPostId === "string" && rawPostId.trim() && rawPostId !== "[id]"
      ? rawPostId.trim()
      : "";

  const [post, setPost] = useState<any>(null);
  const [comments, setComments] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const [hasUpvotedPost, setHasUpvotedPost] = useState(false);
  const [hasDownvotedPost, setHasDownvotedPost] = useState(false);
  const [upvotedComments, setUpvotedComments] = useState<string[]>([]);
  const [downvotedComments, setDownvotedComments] = useState<string[]>([]);
  const [votingCommentIds, setVotingCommentIds] = useState<string[]>([]);
  const [isSending, setIsSending] = useState(false); // 💡 Çift tıklamayı engellemek için loading state'i
  const isOwnPost = Boolean(user?.id && post?.user_id === user.id);
  const postReturnTo = postId ? `/post/${postId}` : "/";

  useEffect(() => {
    if (!postId) {
      setPost(null);
      setComments([]);
      setLoading(false);
      return;
    }

    const fetchPostDetails = async () => {
      try {
        setLoading(true);

        // Gönderinin kendisini çek
        const {
          data: postData,
          error: postError,
        } = await supabase
          .from("posts")
          .select("*")
          .eq("id", postId)
          .maybeSingle();

        let fetchedPost = null;

        if (postError) {
          console.error("Gönderi çekilirken hata:", postError.message);
        } else {
          fetchedPost = postData;
        }

        // Gönderiye ait yorumları çek
        const { data: commentsData, error: commentsError } = await supabase
          .from("comments")
          .select(
            "id,post_id,review_id,user_id,user,avatar,text,content,upvotes,downvotes,created_at",
          )
          .eq("post_id", postId)
          .order("created_at", { ascending: true })
          .limit(100);

        if (commentsError) {
          console.error("Yorumlar çekilirken hata:", commentsError.message);
        }
        const fetchedComments = commentsError ? [] : commentsData || [];

        if (!commentsError) {
          setComments(fetchedComments);
          if (fetchedPost) {
            setPost({ ...fetchedPost, comments: fetchedComments.length });
          }

          if (fetchedPost?.comments !== fetchedComments.length) {
            const { error: syncError } = await supabase.rpc(
              "sync_post_comment_count",
              { p_post_id: postId },
            );

            if (syncError) {
              console.error(
                "Gönderi yorum sayısı senkronlanamadı:",
                syncError.message,
              );
            }
          }
        } else if (fetchedPost) {
          setPost(fetchedPost);
        }

        if (user?.id && fetchedPost) {
          const { data: postVoteData, error: postVoteError } = await supabase
            .from("post_votes")
            .select("post_id")
            .eq("post_id", postId)
            .eq("user_id", user.id)
            .maybeSingle();

          if (!postVoteError) {
            setHasUpvotedPost(!!postVoteData);
          }

          const { data: postDownvoteData, error: postDownvoteError } =
            await supabase
              .from("post_downvotes")
              .select("post_id")
              .eq("post_id", postId)
              .eq("user_id", user.id)
              .maybeSingle();

          if (!postDownvoteError) {
            setHasDownvotedPost(!!postDownvoteData);
          }
        }

        if (user?.id && fetchedComments.length > 0) {
          const commentIds = fetchedComments
            .map((comment: any) => comment.id)
            .filter(Boolean);

          const { data: commentVotesData, error: commentVotesError } =
            await supabase
              .from("comment_votes")
              .select("comment_id")
              .eq("user_id", user.id)
              .in("comment_id", commentIds);

          if (!commentVotesError) {
            setUpvotedComments(
              (commentVotesData || []).map((item: any) => item.comment_id),
            );
          }

          const { data: commentDownvotesData, error: commentDownvotesError } =
            await supabase
              .from("comment_downvotes")
              .select("comment_id")
              .eq("user_id", user.id)
              .in("comment_id", commentIds);

          if (!commentDownvotesError) {
            setDownvotedComments(
              (commentDownvotesData || []).map((item: any) => item.comment_id),
            );
          }
        }
      } catch (error) {
        console.error("Beklenmeyen hata:", error);
      } finally {
        setLoading(false);
      }
    };

    fetchPostDetails();

    const channelSuffix = [
      user?.id || "guest",
      Date.now(),
      Math.random().toString(36).slice(2),
    ].join(":");

    // Gönderideki anlık güncellemeleri dinle
    const postSub = supabase
      .channel(`post-detail:post:${postId}:${channelSuffix}`)
      .on(
        "postgres_changes",
        {
          event: "UPDATE",
          schema: "public",
          table: "posts",
          filter: `id=eq.${postId}`,
        },
        (payload) => setPost(payload.new),
      )
      .subscribe();

    // Yorumlardaki anlık güncellemeleri dinle
    const commentsSub = supabase
      .channel(`post-detail:comments:${postId}:${channelSuffix}`)
      .on(
        "postgres_changes",
        {
          event: "*",
          schema: "public",
          table: "comments",
          filter: `post_id=eq.${postId}`,
        },
        (payload) => {
          if (payload.eventType === "INSERT") {
            setComments((prev: any[] = []) => {
              if (prev.find((c) => c.id === payload.new.id)) return prev;
              const next = [...prev, payload.new];
              setPost((current: any = {}) => ({
                ...current,
                comments: next.length,
              }));
              return next;
            });
          } else if (payload.eventType === "UPDATE") {
            setComments((prev: any[] = []) =>
              prev.map((c) => (c.id === payload.new.id ? payload.new : c)),
            );
          } else if (payload.eventType === "DELETE") {
            setComments((prev: any[] = []) => {
              const next = prev.filter((c) => c.id !== payload.old.id);
              setPost((current: any = {}) => ({
                ...current,
                comments: next.length,
              }));
              return next;
            });
          }
        },
      )
      .subscribe();

    return () => {
      supabase.removeChannel(postSub);
      supabase.removeChannel(commentsSub);
    };
  }, [postId, user?.id]);

  // Gönderiyi Beğen
  const handlePostUpvote = async () => {
    if (!post) return;
    if (!user?.id) {
      router.push(loginRoute(postReturnTo) as any);
      return;
    }
    if (isOwnPost) {
      Alert.alert("Bilgi", "Kendi gönderini oylayamazsın.");
      return;
    }

    const { data, error } = await supabase.rpc("toggle_post_vote", {
      p_post_id: post.id,
    });

    if (error) {
      Alert.alert("Hata", "Faydalı oyu kaydedilemedi: " + error.message);
      return;
    }

    const result = Array.isArray(data) ? data[0] : data;
    setHasUpvotedPost(!!result?.is_voted);
    if (result?.is_voted) setHasDownvotedPost(false);
    setPost({
      ...post,
      upvotes: Number(result?.upvotes || 0),
      downvotes: Number(result?.downvotes || 0),
    });
  };

  // Yorumu Beğen
  const handleCommentUpvote = async (commentId: string) => {
    if (!user?.id) {
      router.push(loginRoute(postReturnTo) as any);
      return;
    }
    const comment = comments.find((item) => item.id === commentId);
    if (user?.id && comment?.user_id === user.id) {
      Alert.alert("Bilgi", "Kendi yorumunu oylayamazsın.");
      return;
    }
    if (votingCommentIds.includes(commentId)) return;

    const wasUpvoted = upvotedComments.includes(commentId);
    const wasDownvoted = downvotedComments.includes(commentId);
    const previousComments = comments;
    const previousUpvoted = upvotedComments;
    const previousDownvoted = downvotedComments;

    setVotingCommentIds((prev) => [...prev, commentId]);
    setUpvotedComments((prev) =>
      wasUpvoted ? prev.filter((id) => id !== commentId) : [...prev, commentId],
    );
    if (wasDownvoted) {
      setDownvotedComments((prev) => prev.filter((id) => id !== commentId));
    }
    setComments((prev: any[] = []) =>
      prev.map((c) => {
        if (c.id !== commentId) return c;
        return {
          ...c,
          upvotes: Math.max(0, Number(c.upvotes || 0) + (wasUpvoted ? -1 : 1)),
          downvotes: Math.max(0, Number(c.downvotes || 0) - (wasDownvoted ? 1 : 0)),
        };
      }),
    );

    const { data, error } = await supabase.rpc("toggle_comment_vote", {
      p_comment_id: commentId,
    });

    if (error) {
      setComments(previousComments);
      setUpvotedComments(previousUpvoted);
      setDownvotedComments(previousDownvoted);
      setVotingCommentIds((prev) => prev.filter((id) => id !== commentId));
      Alert.alert("Hata", "Yorum oyu kaydedilemedi: " + error.message);
      return;
    }

    const result = Array.isArray(data) ? data[0] : data;

    if (result?.is_voted) {
      setUpvotedComments((prev) =>
        prev.includes(commentId) ? prev : [...prev, commentId],
      );
      setDownvotedComments((prev) => prev.filter((id) => id !== commentId));
    } else {
      setUpvotedComments((prev) => prev.filter((id) => id !== commentId));
    }

    setComments((prev: any[] = []) =>
      prev.map((c) =>
        c.id === commentId
          ? {
              ...c,
              upvotes: Number(result?.upvotes || 0),
              downvotes: Number(result?.downvotes || 0),
            }
          : c,
      ),
    );
    setVotingCommentIds((prev) => prev.filter((id) => id !== commentId));
  };

  const handlePostDownvote = async () => {
    if (!post) return;
    if (!user?.id) {
      router.push(loginRoute(postReturnTo) as any);
      return;
    }
    if (isOwnPost) {
      Alert.alert("Bilgi", "Kendi gönderini oylayamazsın.");
      return;
    }

    const { data, error } = await supabase.rpc("toggle_post_downvote", {
      p_post_id: post.id,
    });

    if (error) {
      Alert.alert("Hata", "Olumsuz oy kaydedilemedi: " + error.message);
      return;
    }

    const result = Array.isArray(data) ? data[0] : data;
    setHasDownvotedPost(!!result?.is_downvoted);
    if (result?.is_downvoted) setHasUpvotedPost(false);
    setPost({
      ...post,
      upvotes: Number(result?.upvotes || 0),
      downvotes: Number(result?.downvotes || 0),
    });
  };

  const handleCommentDownvote = async (comment: any) => {
    if (!user?.id) {
      router.push(loginRoute(postReturnTo) as any);
      return;
    }
    if (user?.id && comment?.user_id === user.id) {
      Alert.alert("Bilgi", "Kendi yorumunu oylayamazsın.");
      return;
    }
    if (votingCommentIds.includes(comment.id)) return;

    const wasDownvoted = downvotedComments.includes(comment.id);
    const wasUpvoted = upvotedComments.includes(comment.id);
    const previousComments = comments;
    const previousUpvoted = upvotedComments;
    const previousDownvoted = downvotedComments;

    setVotingCommentIds((prev) => [...prev, comment.id]);
    setDownvotedComments((prev) =>
      wasDownvoted
        ? prev.filter((id) => id !== comment.id)
        : [...prev, comment.id],
    );
    if (wasUpvoted) {
      setUpvotedComments((prev) => prev.filter((id) => id !== comment.id));
    }
    setComments((prev: any[] = []) =>
      prev.map((c) => {
        if (c.id !== comment.id) return c;
        return {
          ...c,
          upvotes: Math.max(0, Number(c.upvotes || 0) - (wasUpvoted ? 1 : 0)),
          downvotes: Math.max(
            0,
            Number(c.downvotes || 0) + (wasDownvoted ? -1 : 1),
          ),
        };
      }),
    );

    const { data, error } = await supabase.rpc("toggle_comment_downvote", {
      p_comment_id: comment.id,
    });

    if (error) {
      setComments(previousComments);
      setUpvotedComments(previousUpvoted);
      setDownvotedComments(previousDownvoted);
      setVotingCommentIds((prev) => prev.filter((id) => id !== comment.id));
      Alert.alert("Hata", "Yorum olumsuz oyu kaydedilemedi: " + error.message);
      return;
    }

    const result = Array.isArray(data) ? data[0] : data;

    if (result?.is_downvoted) {
      setDownvotedComments((prev) =>
        prev.includes(comment.id) ? prev : [...prev, comment.id],
      );
      setUpvotedComments((prev) => prev.filter((id) => id !== comment.id));
    } else {
      setDownvotedComments((prev) =>
        prev.filter((id) => id !== comment.id),
      );
    }

    setComments((prev: any[] = []) =>
      prev.map((c) =>
        c.id === comment.id
          ? {
              ...c,
              upvotes: Number(result?.upvotes || 0),
              downvotes: Number(result?.downvotes || 0),
            }
          : c,
      ),
    );
    setVotingCommentIds((prev) => prev.filter((id) => id !== comment.id));
  };

  const handleReplyToComment = (comment: any) => {
    const name = comment.user || "Kullanıcı";
    const mention = `@${name} `;
    setReplyingToComment(comment);
    setReplyText((current) => {
      if (current.trim().length > 0) return current;
      return mention;
    });
    setTimeout(() => inputRef.current?.focus(), 80);
  };

  const sharePost = async () => {
    if (!post) return;

    await Share.share({
      message: `${post.title || "OtoRehber gönderisi"}\n\n${
        post.content || ""
      }`,
    });
  };

  const deletePost = async () => {
    if (!post?.id || !isOwnPost) return;

    const { error } = await supabase.from("posts").delete().eq("id", post.id);

    if (error) {
      Alert.alert("Hata", "Gönderi silinemedi: " + error.message);
      return;
    }

    router.back();
  };

  const handlePostOptions = () => {
    if (!post) return;

    if (isOwnPost) {
      Alert.alert("Gönderi seçenekleri", undefined, [
        { text: "Paylaş", onPress: sharePost },
        {
          text: "Sil",
          style: "destructive",
          onPress: () =>
            Alert.alert(
              "Gönderiyi sil",
              "Bu gönderiyi silmek istediğine emin misin?",
              [
                { text: "Vazgeç", style: "cancel" },
                { text: "Sil", style: "destructive", onPress: deletePost },
              ],
            ),
        },
        { text: "Vazgeç", style: "cancel" },
      ]);
      return;
    }

    Alert.alert("Gönderi seçenekleri", undefined, [
      { text: "Paylaş", onPress: sharePost },
      {
        text: "Şikayet et",
        style: "destructive",
        onPress: () =>
          void reportContent({
            contentType: "post",
            contentId: post.id,
            contentOwnerId: post.user_id,
          }),
      },
      { text: "Vazgeç", style: "cancel" },
    ]);
  };

  // Yeni Yorum Gönder
  const handleCommentSubmit = async () => {
    if (!replyText.trim() || !post || isSending) return;

    const moderation = validateCleanContent([
      { label: "Yorum", value: replyText },
    ]);

    if (!moderation.ok) {
      Alert.alert("Uygunsuz içerik", moderation.message);
      return;
    }

    try {
      setIsSending(true);

      // 1. Güncel Oturum Kontrolü
      const {
        data: { session },
      } = await supabase.auth.getSession();

      if (!session || !session.user?.id) {
        router.push(loginRoute(postReturnTo) as any);
        return;
      }

      // Metadata içinden ismi güvenle alıyoruz
      const userName =
        user?.name ||
        session.user.user_metadata?.display_name ||
        session.user.user_metadata?.full_name ||
        session.user.email?.split("@")[0] ||
        "Anonim Üye";

      const userAvatar =
        user?.avatar ||
        session.user.user_metadata?.avatar_url ||
        "";

      // 2. Sadece Veritabanının Kesin Beklediği Kolonlarla Temiz Insert Sorgusu
      const nextCommentPayload = {
          content: replyText.trim(),
          text: replyText.trim(),
          post_id: postId,
          user_id: session.user.id,
          user: userName,
          avatar: userAvatar,
          upvotes: 0,
          downvotes: 0,
        };

      const { data: insertedComment, error } = await supabase
        .from("comments")
        .insert(nextCommentPayload)
        .select()
        .single();

      if (error) throw error;

      // 3. Canlı Yenileme ve Alan Temizliği
      setReplyText(""); // TextInput'u anında boşaltıyoruz
      setReplyingToComment(null);

      setComments((prev: any[] = []) => {
        const nextComment = insertedComment || nextCommentPayload;
        if (prev.find((item) => item.id && item.id === nextComment.id)) {
          return prev;
        }
        const next = [...prev, nextComment];
        setPost((current: any = {}) => ({ ...current, comments: next.length }));
        return next;
      });
      scrollToComments();

      const { error: countError } = await supabase.rpc(
        "sync_post_comment_count",
        { p_post_id: postId },
      );

      if (countError) {
        console.error("Gönderi yorum sayısı güncellenemedi:", countError.message);
      }
    } catch (error: any) {
      // 4. Detaylı Konsol Hata Takibi
      console.error("Yorum Detay Hatası:", error);
      Alert.alert(
        "Hata",
        "Yorum gönderilirken bir sorun oluştu: " + error.message,
      );
    } finally {
      setIsSending(false);
    }
  };

  if (loading) {
    return (
      <SafeAreaView
        style={[styles.container, { backgroundColor: palette.background }]}
        edges={["top"]}
      >
        <Stack.Screen options={{ headerShown: false }} />
        <View
          style={[
            styles.header,
            {
              backgroundColor: palette.background,
              borderBottomColor: palette.border,
            },
          ]}
        >
          <TouchableOpacity
            onPress={() => router.back()}
            style={styles.headerBtn}
          >
            <FontAwesome6 name="arrow-left" size={18} color={palette.text} />
          </TouchableOpacity>
          <Text style={[styles.headerTitle, { color: palette.text }]}>
            Yükleniyor...
          </Text>
          <View style={styles.headerBtn} />
        </View>
        <View
          style={{ flex: 1, justifyContent: "center", alignItems: "center" }}
        >
          <ActivityIndicator size="large" color={Colors.orange} />
        </View>
      </SafeAreaView>
    );
  }

  if (!post) {
    return (
      <SafeAreaView
        style={[styles.container, { backgroundColor: palette.background }]}
        edges={["top"]}
      >
        <Stack.Screen options={{ headerShown: false }} />
        <View
          style={[
            styles.header,
            {
              backgroundColor: palette.background,
              borderBottomColor: palette.border,
            },
          ]}
        >
          <TouchableOpacity
            onPress={() => router.back()}
            style={styles.headerBtn}
          >
            <FontAwesome6 name="arrow-left" size={18} color={palette.text} />
          </TouchableOpacity>
          <Text style={[styles.headerTitle, { color: palette.text }]}>Hata</Text>
          <View style={styles.headerBtn} />
        </View>
        <Text
          style={{
            color: palette.muted,
            textAlign: "center",
            marginTop: 40,
          }}
        >
          Gönderi bulunamadı.
        </Text>
      </SafeAreaView>
    );
  }

  const postAuthorName = isOwnPost && user?.name ? user.name : post.user || "Anonim";
  const postAuthorAvatar = isOwnPost && user?.avatar ? user.avatar : post.avatar;
  const shouldShowPostAvatarImage = !isGeneratedAvatar(postAuthorAvatar);

  return (
    <SafeAreaView
      style={[styles.container, { backgroundColor: palette.background }]}
      edges={["top"]}
    >
      <Stack.Screen options={{ headerShown: false }} />

      {/* Üst Kısım / Header */}
      <View
        style={[
          styles.header,
          { backgroundColor: palette.background, borderBottomColor: palette.border },
        ]}
      >
        <TouchableOpacity
          onPress={() => router.back()}
          style={styles.headerBtn}
        >
          <FontAwesome6 name="arrow-left" size={18} color={palette.text} />
        </TouchableOpacity>
        <Text style={[styles.headerTitle, { color: palette.text }]}>
          Gönderi
        </Text>
        <TouchableOpacity style={styles.headerBtn} onPress={handlePostOptions}>
          <FontAwesome6 name="ellipsis-vertical" size={18} color={palette.text} />
        </TouchableOpacity>
      </View>

      <KeyboardAvoidingView
        style={{ flex: 1 }}
        behavior={Platform.OS === "ios" ? "padding" : "height"}
        keyboardVerticalOffset={Platform.OS === "ios" ? 0 : 0}
      >
        <ScrollView
          ref={scrollRef}
          style={styles.scrollContainer}
          contentContainerStyle={styles.scrollContent}
          showsVerticalScrollIndicator={false}
          keyboardShouldPersistTaps="handled"
        >
          {/* Orijinal Gönderi Kartı */}
          <View
            style={[
              styles.postCard,
              { backgroundColor: palette.background },
            ]}
          >
            <TouchableOpacity
              style={styles.postHeader}
              activeOpacity={0.75}
              onPress={() => {
                if (post.user_id) router.push(`/user/${post.user_id}` as any);
              }}
            >
              {shouldShowPostAvatarImage ? (
                <Image
                  source={{ uri: postAuthorAvatar }}
                  style={styles.avatar}
                />
              ) : (
                <View
                  style={[
                    styles.avatarFallback,
                    { backgroundColor: palette.elevated, borderColor: palette.border },
                  ]}
                >
                  <Text
                    style={[
                      styles.avatarFallbackText,
                      { color: palette.text },
                    ]}
                  >
                    {getInitials(postAuthorName)}
                  </Text>
                </View>
              )}
              <View style={{ flex: 1 }}>
                <View style={{ flexDirection: "row", alignItems: "center" }}>
                  <Text style={[styles.postAuthor, { color: palette.text }]}>
                    {postAuthorName}
                  </Text>
                  <Text style={[styles.postDot, { color: palette.muted }]}>
                    {" "}
                    •{" "}
                  </Text>
                  <Text style={styles.postCarBadge}>
                    {post.car || "Bilinmiyor"}
                  </Text>
                </View>
                <Text style={[styles.postTime, { color: palette.muted }]}>
                  {post.created_at
                    ? new Date(post.created_at).toLocaleDateString("tr-TR")
                    : "Yeni"}
                </Text>
              </View>
            </TouchableOpacity>
            {!hasAutoGeneratedTitle(post) ? (
              <Text style={[styles.postTitle, { color: palette.text }]}>
                {post.title}
              </Text>
            ) : null}
            {Array.isArray(post.topic_tags) && post.topic_tags.length > 0 ? (
              <View style={styles.topicTags}>
                {post.topic_tags.map((tag: string) => (
                  <View
                    key={`${post.id}-${tag}`}
                    style={[
                      styles.topicTag,
                      { backgroundColor: palette.elevated, borderColor: palette.border },
                    ]}
                  >
                    <Text style={styles.topicTagText}>{tag}</Text>
                  </View>
                ))}
              </View>
            ) : null}
            <Text style={[styles.postContent, { color: palette.softText }]}>
              {post.content}
            </Text>
            {Array.isArray(post.images) && post.images.length > 0 ? (
              <PhotoCarousel
                images={post.images}
                height={260}
                style={styles.postPhotoCarousel}
              />
            ) : null}
            <View
              style={[styles.interactionRow, { borderTopColor: palette.border }]}
            >
              <View
                style={[
                  styles.upvoteGroup,
                  { backgroundColor: palette.card, borderColor: palette.border },
                ]}
              >
                <TouchableOpacity
                  style={[styles.iconBtn, isOwnPost && styles.disabledVoteBtn]}
                  onPress={handlePostUpvote}
                  disabled={isOwnPost}
                >
                  <FontAwesome6
                    name="arrow-up"
                    size={16}
                    color={
                      isOwnPost
                        ? palette.border
                        : hasUpvotedPost
                          ? Colors.orange
                          : palette.muted
                    }
                  />
                </TouchableOpacity>
                <Text
                  style={[
                    styles.upvoteCount,
                    { color: palette.text },
                    hasUpvotedPost && { color: Colors.orange },
                  ]}
                >
                  {post.upvotes || 0}
                </Text>
                <TouchableOpacity
                  style={[styles.iconBtn, isOwnPost && styles.disabledVoteBtn]}
                  onPress={handlePostDownvote}
                  disabled={isOwnPost}
                >
                  <FontAwesome6
                    name="arrow-down"
                    size={16}
                    color={
                      isOwnPost
                        ? palette.border
                        : hasDownvotedPost
                          ? "#ef4444"
                          : palette.muted
                    }
                  />
                </TouchableOpacity>
                {Number(post.downvotes || 0) > 0 && (
                  <Text
                    style={[
                      styles.upvoteCount,
                      {
                        color: hasDownvotedPost ? "#ef4444" : palette.muted,
                      },
                    ]}
                  >
                    {post.downvotes}
                  </Text>
                )}
              </View>
              <View
                style={[
                  styles.commentBtn,
                  { backgroundColor: palette.card, borderColor: palette.border },
                ]}
              >
                <FontAwesome6
                  name="message"
                  size={14}
                  color={palette.muted}
                />
                <Text style={[styles.commentCount, { color: palette.muted }]}>
                  {comments.length} Yorum
                </Text>
              </View>
            </View>
            {isOwnPost ? (
              <View style={styles.ownPostVoteHint}>
                <FontAwesome6
                  name="circle-info"
                  size={11}
                  color={palette.muted}
                />
                <Text style={[styles.ownPostVoteHintText, { color: palette.muted }]}>
                  Kendi içeriğini oylayamazsın.
                </Text>
              </View>
            ) : null}
          </View>

          <View style={[styles.divider, { backgroundColor: palette.card }]} />

          {/* Yorumlar Listesi */}
          <Text style={[styles.commentsTitle, { color: palette.text }]}>
            Yorumlar ({comments.length})
          </Text>
          {comments.map((comment) => {
            const isOwnComment = Boolean(
              user?.id && comment.user_id === user.id,
            );
            const commentName =
              isOwnComment && user?.name ? user.name : comment.user || "Anonim";
            const commentAvatar =
              isOwnComment && user?.avatar ? user.avatar : comment.avatar;
            const shouldShowAvatarImage = !isGeneratedAvatar(commentAvatar);

            return (
            <View key={comment.id} style={styles.commentCard}>
              {shouldShowAvatarImage ? (
                <Image
                  source={{ uri: commentAvatar }}
                  style={styles.commentAvatar}
                />
              ) : (
                <View
                  style={[
                    styles.commentAvatarFallback,
                    { backgroundColor: palette.elevated },
                  ]}
                >
                  <Text
                    style={[
                      styles.commentAvatarFallbackText,
                      { color: palette.text },
                    ]}
                  >
                    {getInitials(commentName)}
                  </Text>
                </View>
              )}
              <View style={styles.commentBody}>
                <View style={styles.commentHeader}>
                  <Text style={[styles.commentUser, { color: palette.text }]}>
                    {commentName}
                  </Text>
                </View>
                <Text style={[styles.commentText, { color: palette.softText }]}>
                  {comment.content || comment.text}
                </Text>
                <View style={styles.commentActions}>
                  <View style={styles.commentUpvoteGroup}>
                    <TouchableOpacity
                      onPress={() => handleCommentUpvote(comment.id)}
                      disabled={isOwnComment || votingCommentIds.includes(comment.id)}
                    >
                      {votingCommentIds.includes(comment.id) ? (
                        <ActivityIndicator size="small" color={Colors.orange} />
                      ) : (
                        <FontAwesome6
                          name="arrow-up"
                          size={12}
                          color={
                            isOwnComment
                              ? palette.border
                              : upvotedComments.includes(comment.id)
                              ? Colors.orange
                              : palette.muted
                          }
                        />
                      )}
                    </TouchableOpacity>
                    <Text
                      style={[
                        styles.commentUpvoteCount,
                        { color: palette.muted },
                        upvotedComments.includes(comment.id) && {
                          color: Colors.orange,
                        },
                      ]}
                    >
                      {comment.upvotes || 0}
                    </Text>
                    <TouchableOpacity
                      onPress={() => handleCommentDownvote(comment)}
                      disabled={isOwnComment || votingCommentIds.includes(comment.id)}
                    >
                      <FontAwesome6
                        name="arrow-down"
                        size={12}
                        color={
                          isOwnComment
                            ? palette.border
                            : downvotedComments.includes(comment.id)
                            ? "#ef4444"
                            : palette.muted
                        }
                      />
                    </TouchableOpacity>
                    {Number(comment.downvotes || 0) > 0 && (
                      <Text
                        style={[
                          styles.commentUpvoteCount,
                          {
                            color: downvotedComments.includes(comment.id)
                              ? "#ef4444"
                              : palette.muted,
                          },
                        ]}
                      >
                        {comment.downvotes}
                      </Text>
                    )}
                  </View>
                  <TouchableOpacity onPress={() => handleReplyToComment(comment)}>
                    <Text style={[styles.replyText, { color: palette.muted }]}>
                      Yanıtla
                    </Text>
                  </TouchableOpacity>
                </View>
              </View>
            </View>
            );
          })}
        </ScrollView>

        {/* Yorum Yazma Alanı */}
        <View
          style={[
            styles.inputArea,
            {
              backgroundColor: palette.background,
              borderTopColor: palette.border,
              paddingBottom: Math.max(insets.bottom, 12),
            },
          ]}
        >
          {replyingToComment ? (
            <View
              style={[
                styles.replyingBanner,
                { backgroundColor: palette.card, borderColor: palette.border },
              ]}
            >
              <Text style={[styles.replyingText, { color: palette.muted }]}>
                {replyingToComment.user || "Kullanıcı"} kullanıcısına yanıt
              </Text>
              <TouchableOpacity
                onPress={() => {
                  setReplyingToComment(null);
                  setReplyText("");
                }}
                hitSlop={8}
              >
                <FontAwesome6 name="xmark" size={12} color={palette.muted} />
              </TouchableOpacity>
            </View>
          ) : null}
          <View style={styles.inputRow}>
            <TextInput
              ref={inputRef}
              style={[
                styles.input,
                {
                  backgroundColor: palette.card,
                  borderColor: palette.border,
                  color: palette.text,
                },
              ]}
              placeholder="Fikirlerini paylaş veya yanıtla..."
              placeholderTextColor={palette.muted}
              value={replyText}
              onChangeText={setReplyText}
              onFocus={scrollToComments}
              multiline
            />
            <TouchableOpacity
              style={[
                styles.sendBtn,
                (!replyText.trim() || isSending) && styles.sendBtnDisabled,
              ]}
              disabled={!replyText.trim() || isSending}
              activeOpacity={0.8}
              onPress={handleCommentSubmit}
            >
              {isSending ? (
                <ActivityIndicator size="small" color={Colors.white} />
              ) : (
                <FontAwesome6
                  name="paper-plane"
                  size={16}
                  color={replyText.trim() ? Colors.white : palette.muted}
                />
              )}
            </TouchableOpacity>
          </View>
        </View>
      </KeyboardAvoidingView>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: Colors.navyMain },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 10,
    paddingVertical: 12,
    backgroundColor: Colors.navyMain,
    borderBottomWidth: 1,
    borderBottomColor: Colors.navyBorder,
  },
  headerBtn: {
    width: 40,
    height: 40,
    justifyContent: "center",
    alignItems: "center",
  },
  headerTitle: { fontSize: 16, fontWeight: "700", color: Colors.white },
  scrollContainer: { flex: 1 },
  scrollContent: { padding: 20, paddingBottom: 28 },
  postCard: {
    backgroundColor: Colors.navyMain,
    paddingBottom: 16,
  },
  postHeader: { flexDirection: "row", alignItems: "center", marginBottom: 12 },
  avatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
    marginRight: 12,
    backgroundColor: Colors.navyBorder,
  },
  avatarFallback: {
    width: 40,
    height: 40,
    borderRadius: 20,
    marginRight: 12,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
  },
  avatarFallbackText: {
    fontSize: 13,
    fontWeight: "900",
  },
  postAuthor: { color: Colors.white, fontWeight: "700", fontSize: 14 },
  postDot: { color: Colors.textMuted, fontSize: 14 },
  postCarBadge: { color: Colors.orange, fontWeight: "700", fontSize: 13 },
  postTime: { color: Colors.textMuted, fontSize: 11, marginTop: 2 },
  postTitle: {
    color: Colors.white,
    fontSize: 18,
    fontWeight: "800",
    marginBottom: 8,
  },
  topicTags: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 7,
    marginBottom: 10,
  },
  topicTag: {
    borderRadius: 9,
    borderWidth: 1,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  topicTagText: {
    color: Colors.orange,
    fontSize: 11,
    fontWeight: "700",
  },
  postContent: {
    color: Colors.gray300,
    fontSize: 14,
    lineHeight: 22,
    marginBottom: 16,
  },
  postPhotoCarousel: { marginBottom: 16 },
  interactionRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    borderTopWidth: 1,
    borderTopColor: Colors.navyBorder,
    paddingTop: 12,
  },
  upvoteGroup: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: Colors.navyCard,
    borderRadius: 20,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderWidth: 1,
    borderColor: Colors.navyBorder,
  },
  iconBtn: { padding: 4 },
  disabledVoteBtn: { opacity: 0.45 },
  ownPostVoteHint: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    marginTop: 8,
  },
  ownPostVoteHintText: {
    fontSize: 11,
    lineHeight: 15,
  },
  upvoteCount: {
    color: Colors.white,
    fontWeight: "700",
    marginHorizontal: 12,
    fontSize: 13,
  },
  commentBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    backgroundColor: Colors.navyCard,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: Colors.navyBorder,
  },
  commentCount: { color: Colors.textMuted, fontSize: 12, fontWeight: "600" },

  divider: {
    height: 6,
    backgroundColor: Colors.navyCard,
    marginHorizontal: -20,
    marginVertical: 16,
  },

  commentsTitle: {
    fontSize: 16,
    fontWeight: "800",
    color: Colors.white,
    marginBottom: 20,
  },
  commentCard: {
    flexDirection: "row",
    marginBottom: 24,
    alignItems: "flex-start",
  },
  commentAvatar: {
    width: 32,
    height: 32,
    borderRadius: 16,
    marginRight: 12,
    backgroundColor: Colors.navyBorder,
  },
  commentAvatarFallback: {
    width: 32,
    height: 32,
    borderRadius: 16,
    marginRight: 12,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: Colors.navyBorder,
  },
  commentAvatarFallbackText: {
    fontSize: 11,
    fontWeight: "900",
    color: Colors.white,
  },
  commentBody: { flex: 1 },
  commentHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 4,
  },
  commentUser: { color: Colors.white, fontWeight: "700", fontSize: 13 },
  commentBadge: { color: Colors.orange, fontWeight: "600", fontSize: 11 },
  commentText: { color: Colors.gray300, fontSize: 13, lineHeight: 20 },
  commentActions: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 8,
    gap: 16,
  },
  commentUpvoteGroup: { flexDirection: "row", alignItems: "center", gap: 8 },
  commentUpvoteCount: {
    color: Colors.textMuted,
    fontWeight: "600",
    fontSize: 11,
  },
  replyText: { color: Colors.textMuted, fontWeight: "600", fontSize: 12 },

  inputArea: {
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderTopWidth: 1,
    borderTopColor: Colors.navyBorder,
    backgroundColor: Colors.navyMain,
  },
  replyingBanner: {
    minHeight: 32,
    borderRadius: 12,
    borderWidth: 1,
    paddingHorizontal: 12,
    marginBottom: 8,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  replyingText: {
    flex: 1,
    fontSize: 12,
    fontWeight: "700",
  },
  inputRow: {
    flexDirection: "row",
    alignItems: "flex-end",
  },
  input: {
    flex: 1,
    backgroundColor: Colors.navyCard,
    borderWidth: 1,
    borderColor: Colors.navyBorder,
    borderRadius: 20,
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 12,
    maxHeight: 100,
    color: Colors.white,
    fontSize: 14,
  },
  sendBtn: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: Colors.orange,
    justifyContent: "center",
    alignItems: "center",
    marginLeft: 12,
    marginBottom: 2,
    boxShadow: "0 2px 4px rgba(249, 115, 22, 0.5)",
    elevation: 5,
  },
  sendBtnDisabled: {
    backgroundColor: Colors.navyCard,
    boxShadow: "none",
    elevation: 0,
    borderWidth: 1,
    borderColor: Colors.navyBorder,
  },
});
